export {BienvenidaPage} from "./bienvenida/bienvenida";
export {HomePage}  from "./home/home";
export {TabsPage}  from "./tabs/tabs";
export {PromoPage} from './promo/promo'
export {ListaPage} from './lista/lista'
export {FavoritasPage} from './favoritas/favoritas'
export {NosotrosPage} from './nosotros/nosotros'
export {LoginPage} from './login/login'
export {RegistrarPage} from './registrar/registrar'
